-- SCHEMA SQL UNTUK SUPABASE DATABASE
-- Salin seluruh skrip di bawah ini dan jalankan di SQL Editor Supabase Anda.

-- ⚠️ CATATAN: Jika Anda mendapatkan error "relation 'cars' already exists", itu berarti tabel sudah pernah dibuat sebelumnya.
-- Jika Anda ingin MENGHAPUS tabel lama dan MEMBUAT ULANG semuanya dari awal (Data lama akan terhapus!),
-- silakan hapus tanda "--" pada baris DROP TABLE di bawah ini sebelum menjalankan query:
-- DROP TABLE IF EXISTS public.comments CASCADE;
-- DROP TABLE IF EXISTS public.private_messages CASCADE;
-- DROP TABLE IF EXISTS public.cars CASCADE;

-- 1. Tabel Mobil (cars)
CREATE TABLE IF NOT EXISTS public.cars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    price bigint NOT NULL,
    year integer NOT NULL,
    transmission text NOT NULL CHECK (transmission IN ('Manual', 'Matik')),
    fuel_type text NOT NULL CHECK (fuel_type IN ('Bensin', 'Diesel', 'Listrik', 'Hybrid')),
    mileage integer NOT NULL,
    condition_type text DEFAULT 'Bekas' CHECK (condition_type IN ('Baru', 'Bekas')),
    status text DEFAULT 'Tersedia' CHECK (status IN ('Tersedia', 'Booking', 'Terjual')),
    description text NOT NULL,
    tax_expiration text,
    engine_cc integer NOT NULL,
    passenger_capacity integer DEFAULT 7,
    color text NOT NULL,
    images text[] DEFAULT '{}'::text[] NOT NULL, -- Array URL gambar mobil
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Aktifkan Row Level Security (RLS) pada tabel cars
ALTER TABLE public.cars ENABLE ROW LEVEL SECURITY;

-- Buat Policy agar semua pengunjung umum bisa membaca data mobil
CREATE POLICY "Allow public read access on cars" ON public.cars
    FOR SELECT TO public USING (true);

-- Buat Policy agar Admin dengan API Key Service Role (sb_secret) memiliki hak penuh (ALL)
CREATE POLICY "Allow full access for service_role on cars" ON public.cars
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- 2. Tabel Komentar Publik (comments)
CREATE TABLE IF NOT EXISTS public.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id bigint REFERENCES public.cars(id) ON DELETE CASCADE NOT NULL,
    sender_name text NOT NULL,
    comment_text text NOT NULL,
    is_approved boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on comments" ON public.comments
    FOR SELECT TO public USING (is_approved = true);

CREATE POLICY "Allow public insert access on comments" ON public.comments
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow full access for service_role on comments" ON public.comments
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- 3. Tabel Pesan Privat (private_messages)
CREATE TABLE IF NOT EXISTS public.private_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id bigint REFERENCES public.cars(id) ON DELETE SET NULL,
    sender_name text NOT NULL,
    sender_phone text NOT NULL,
    message_content text NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.private_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert access on private_messages" ON public.private_messages
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow full access for service_role on private_messages" ON public.private_messages
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ========================================================
-- DATA CONTOH AWAL (INITIAL SAMPLE DATA)
-- ========================================================

INSERT INTO public.cars (title, price, year, transmission, fuel_type, mileage, condition_type, status, description, tax_expiration, engine_cc, passenger_capacity, color, images)
VALUES 
(
    'Toyota Avanza Veloz 1.5 AT 2019', 
    175000000, 
    2019, 
    'Matik', 
    'Bensin', 
    45000, 
    'Bekas', 
    'Tersedia', 
    'Toyota Avanza Veloz facelift tahun 2019 transmisi otomatis (A/T) dengan kondisi super istimewa. Unit tangan pertama dari baru, servis record resmi Toyota Medan, AC double blower dingin membeku. Bodi mulus bebas dempul, kaki-kaki kokoh senyap khas Veloz. Surat lengkap, pajak panjang, siap pakai dalam dan luar kota!', 
    'Oktober 2026', 
    1500, 
    7, 
    'Putih Metalik', 
    ARRAY[
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=800'
    ]
),
(
    'Toyota Innova Reborn 2.4 G Diesel AT 2018', 
    295000000, 
    2018, 
    'Matik', 
    'Diesel', 
    60000, 
    'Bekas', 
    'Booking', 
    'Innova Reborn G Diesel 2.4 A/T 2018. Mesin diesel 2GD-FTV legendaris yang sangat bertenaga dan irit bahan bakar. Interior original bersih and wangi, rawatan rutin bengkel resmi. Transmisi matik sangat responsif. Kelistrikan dan sensor normal tanpa kendala. Sangat cocok sebagai mobil keluarga berkelas di Medan.', 
    'November 2026', 
    2400, 
    7, 
    'Hitam Metalik', 
    ARRAY[
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800'
    ]
),
(
    'Honda Brio RS 1.2 AT 2020', 
    145000000, 
    2020, 
    'Matik', 
    'Bensin', 
    30000, 
    'Bekas', 
    'Tersedia', 
    'Honda Brio RS tipe tertinggi tahun 2020. Tampilan sporty dengan velg two-tone original RS, interior jahitan orange khas RS, head unit touchscreen modern. Mesin i-VTEC 1.2L lincah, sangat irit BBM dan mudah diparkir di kemacetan kota Medan. Surat-surat aman terjamin lengkap.', 
    'Desember 2026', 
    1200, 
    5, 
    'Orange Phoenix', 
    ARRAY[
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800'
    ]
),
(
    'Mitsubishi Xpander Ultimate 1.5 AT 2019', 
    215000000, 
    2019, 
    'Matik', 
    'Bensin', 
    50000, 
    'Bekas', 
    'Terjual', 
    'Mitsubishi Xpander Ultimate A/T 2019 warna silver metalik. Fitur keselamatan lengkap (Active Stability Control, Hill Start Assist), interior bernuansa beige yang mewah dengan panel kayu. Jok dilapis kulit sintetis rapi, ban tebal, cat original bawaan pabrik. Istimewa dan siap COD wilayah Medan.', 
    'Maret 2027', 
    1500, 
    7, 
    'Silver Metalik', 
    ARRAY[
        'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=800'
    ]
),
(
    'Wuling Confero S 1.5 C MT 2019', 
    105000000, 
    2019, 
    'Manual', 
    'Bensin', 
    55000, 
    'Bekas', 
    'Tersedia', 
    'Wuling Confero S 1.5 C 2019 manual, kabin lapang dengan kapasitas 8 penumpang. AC double blower dingin merata, suspensi empuk untuk perjalanan keluarga. Tampilan gagah dengan aksen hitam di bumper dan overfender. Kualitas terjaga, servis rutin berkala, siap bawa pulang langsung ke rumah Anda.', 
    'Agustus 2026', 
    1500, 
    8, 
    'Merah Burgundy', 
    ARRAY[
        'images/owner.png',
        'https://images.unsplash.com/photo-1581540222194-0def2dda95d8?auto=format&fit=crop&q=80&w=800'
    ]
);
